INSERT INTO products (id, name, description, category, default_color)
VALUES
    (
        'tv-001',
        'Premium 65-inch 4K Smart TV',
        'A premium 65-inch 4K smart television designed for an interactive 3D product experience.',
        'Television',
        'Graphite'
    ),
    (
        'refrigerator-001',
        'Premium French Door Refrigerator',
        'A premium French door refrigerator designed for an interactive 3D product experience.',
        'Refrigerator',
        'Stainless Steel'
    );

INSERT INTO product_colors (product_id, color_name, sort_order)
VALUES
    ('tv-001', 'Graphite', 1),
    ('tv-001', 'Silver', 2),
    ('tv-001', 'Midnight', 3),
    ('tv-001', 'Ivory', 4),
    ('refrigerator-001', 'Stainless Steel', 1),
    ('refrigerator-001', 'Black Stainless', 2),
    ('refrigerator-001', 'White', 3),
    ('refrigerator-001', 'Slate', 4);

INSERT INTO product_features (
    id,
    product_id,
    name,
    description,
    category,
    model_node_name,
    sort_order,
    position_x,
    position_y,
    position_z,
    camera_x,
    camera_y,
    camera_z
)
VALUES
    (
        'display',
        'tv-001',
        'Display',
        '65-inch 4K QLED panel with high brightness and wide viewing angles for cinematic picture quality.',
        'Hardware',
        'display',
        1,
        0.0,
        0.9,
        0.04,
        0.0,
        1.0,
        3.2
    ),
    (
        'hdmi-ports',
        'tv-001',
        'HDMI Ports',
        'Rear HDMI 2.1 inputs supporting 4K 120 Hz, eARC, and variable refresh rate for consoles and soundbars.',
        'Connectivity',
        'hdmi',
        2,
        0.55,
        0.35,
        -0.12,
        1.8,
        0.6,
        2.4
    ),
    (
        'usb-port',
        'tv-001',
        'USB Port',
        'Side USB ports for media playback and service accessories without blocking HDMI cables.',
        'Connectivity',
        'usb',
        3,
        0.72,
        0.45,
        0.0,
        2.0,
        0.7,
        2.2
    ),
    (
        'speakers',
        'tv-001',
        'Speakers',
        'Down-firing 2.1 speaker system tuned for dialogue clarity and supported cinematic audio formats.',
        'Audio',
        'speaker',
        4,
        0.0,
        0.12,
        0.06,
        0.0,
        0.4,
        2.6
    ),
    (
        'power-button',
        'tv-001',
        'Power Button',
        'Bezel power control for turning the television on and cycling through input sources.',
        'Controls',
        'power-button',
        5,
        0.68,
        0.08,
        0.03,
        1.6,
        0.3,
        2.3
    ),
    (
        'remote-sensor',
        'tv-001',
        'Remote Sensor',
        'Front IR and Bluetooth receiver that accepts commands from the included smart remote.',
        'Controls',
        'remote-sensor',
        6,
        0.0,
        0.06,
        0.05,
        0.0,
        0.2,
        2.4
    ),
    (
        'wifi',
        'tv-001',
        'Wi-Fi',
        'Built-in Wi-Fi 6 radio for streaming apps, firmware updates, and smart-home control.',
        'Connectivity',
        'wifi',
        7,
        -0.35,
        0.4,
        -0.08,
        -1.4,
        0.7,
        2.5
    ),
    (
        'ethernet-port',
        'tv-001',
        'Ethernet Port',
        'Rear gigabit Ethernet jack for a wired network connection when Wi-Fi is unavailable.',
        'Connectivity',
        'ethernet',
        8,
        0.48,
        0.28,
        -0.12,
        1.7,
        0.5,
        2.3
    ),
    (
        'processor',
        'tv-001',
        'Processor',
        '4K picture processor that handles upscaling, motion smoothing, and on-device smart TV apps.',
        'Internal',
        'processor',
        9,
        0.0,
        0.45,
        -0.1,
        0.0,
        0.8,
        2.8
    ),
    (
        'stand',
        'tv-001',
        'Stand',
        'Dual-pedestal metal stand that supports tabletop placement and aligns with VESA wall-mount points.',
        'Design',
        'stand',
        10,
        0.0,
        -0.35,
        0.15,
        0.0,
        0.2,
        3.0
    ),
    (
        'freezer',
        'refrigerator-001',
        'Freezer',
        'Full-width bottom freezer drawer with organized bins for frozen food storage.',
        'Storage',
        'freezer',
        1,
        0.0,
        -0.55,
        0.2,
        0.0,
        -0.2,
        3.2
    ),
    (
        'refrigerator-compartment',
        'refrigerator-001',
        'Refrigerator Compartment',
        'Upper French-door fresh food compartment with adjustable shelves and wide door bins.',
        'Storage',
        'refrigerator-compartment',
        2,
        0.0,
        0.55,
        0.18,
        0.0,
        0.8,
        3.4
    ),
    (
        'water-dispenser',
        'refrigerator-001',
        'Water Dispenser',
        'External filtered water dispenser built into the left door for measured glass filling.',
        'Convenience',
        'water-dispenser',
        3,
        -0.28,
        0.35,
        0.42,
        -1.4,
        0.6,
        2.8
    ),
    (
        'ice-maker',
        'refrigerator-001',
        'Ice Maker',
        'Automatic ice maker that produces and stores cubed ice for the dispenser and freezer bin.',
        'Convenience',
        'ice-maker',
        4,
        -0.22,
        0.2,
        0.15,
        -1.2,
        0.5,
        2.6
    ),
    (
        'door',
        'refrigerator-001',
        'Door',
        'Fingerprint-resistant French doors with soft-close hinges and full-height handles.',
        'Design',
        'door',
        5,
        0.32,
        0.4,
        0.4,
        1.6,
        0.7,
        2.9
    ),
    (
        'compressor',
        'refrigerator-001',
        'Compressor',
        'Variable-speed inverter compressor mounted at the rear base for efficient cooling with low noise.',
        'Internal',
        'compressor',
        6,
        0.0,
        -0.7,
        -0.25,
        0.0,
        -0.3,
        3.0
    ),
    (
        'temperature-controls',
        'refrigerator-001',
        'Temperature Controls',
        'Digital interior panel for independent refrigerator, freezer, and vacation temperature modes.',
        'Controls',
        'temperature-controls',
        7,
        0.18,
        0.85,
        0.12,
        1.1,
        1.2,
        2.7
    ),
    (
        'shelves',
        'refrigerator-001',
        'Shelves',
        'Spill-proof glass shelves that can be repositioned to fit tall bottles and large platters.',
        'Storage',
        'shelves',
        8,
        0.0,
        0.5,
        0.05,
        0.0,
        0.7,
        2.8
    ),
    (
        'door-alarm',
        'refrigerator-001',
        'Door Alarm',
        'Audible alert that sounds when a door remains open longer than two minutes.',
        'Controls',
        'door-alarm',
        9,
        0.38,
        0.75,
        0.38,
        1.5,
        1.0,
        2.6
    ),
    (
        'interior-light',
        'refrigerator-001',
        'Interior Light',
        'LED lighting zones that illuminate the fresh food compartment and freezer drawer.',
        'Hardware',
        'interior-light',
        10,
        0.0,
        0.95,
        0.08,
        0.0,
        1.3,
        2.9
    );

INSERT INTO feature_specifications (product_id, feature_id, name, value, sort_order)
VALUES
    ('tv-001', 'display', 'Panel Type', '4K QLED', 1),
    ('tv-001', 'display', 'Screen Size', '65 inches', 2),
    ('tv-001', 'display', 'Refresh Rate', '120 Hz', 3),
    ('tv-001', 'display', 'HDR', 'Dolby Vision and HDR10+', 4),
    ('tv-001', 'hdmi-ports', 'Ports', '4 HDMI 2.1', 1),
    ('tv-001', 'hdmi-ports', 'eARC', 'HDMI 2', 2),
    ('tv-001', 'hdmi-ports', 'VRR', 'Supported', 3),
    ('tv-001', 'usb-port', 'Ports', '2 USB 2.0', 1),
    ('tv-001', 'usb-port', 'Media Playback', 'Photos, video, audio', 2),
    ('tv-001', 'speakers', 'Configuration', '2.1 channel', 1),
    ('tv-001', 'speakers', 'Output', '40W', 2),
    ('tv-001', 'speakers', 'Audio Formats', 'Dolby Atmos', 3),
    ('tv-001', 'power-button', 'Location', 'Bottom-right bezel', 1),
    ('tv-001', 'power-button', 'Functions', 'Power, source cycle', 2),
    ('tv-001', 'remote-sensor', 'Type', 'IR and Bluetooth', 1),
    ('tv-001', 'remote-sensor', 'Angle', 'Wide-angle front IR', 2),
    ('tv-001', 'wifi', 'Standard', 'Wi-Fi 6', 1),
    ('tv-001', 'wifi', 'Bands', 'Dual-band 2.4/5 GHz', 2),
    ('tv-001', 'ethernet-port', 'Standard', 'Gigabit Ethernet', 1),
    ('tv-001', 'ethernet-port', 'Location', 'Rear I/O panel', 2),
    ('tv-001', 'processor', 'Engine', '4K AI picture processor', 1),
    ('tv-001', 'processor', 'Features', 'Upscaling, motion smoothing', 2),
    ('tv-001', 'stand', 'Type', 'Dual-pedestal metal stand', 1),
    ('tv-001', 'stand', 'VESA', '400 x 300 mm', 2),
    ('refrigerator-001', 'freezer', 'Type', 'Bottom freezer drawer', 1),
    ('refrigerator-001', 'freezer', 'Capacity', '8.5 cu. ft.', 2),
    ('refrigerator-001', 'freezer', 'Temperature', '-1 F to 5 F', 3),
    ('refrigerator-001', 'refrigerator-compartment', 'Capacity', '18.2 cu. ft.', 1),
    ('refrigerator-001', 'refrigerator-compartment', 'Temperature', '34 F to 42 F', 2),
    ('refrigerator-001', 'refrigerator-compartment', 'Layout', 'French door', 3),
    ('refrigerator-001', 'water-dispenser', 'Type', 'External door dispenser', 1),
    ('refrigerator-001', 'water-dispenser', 'Filtration', 'Carbon water filter', 2),
    ('refrigerator-001', 'water-dispenser', 'Flow', 'Measured fill', 3),
    ('refrigerator-001', 'ice-maker', 'Type', 'In-door automatic', 1),
    ('refrigerator-001', 'ice-maker', 'Output', 'Up to 4.5 lbs/day', 2),
    ('refrigerator-001', 'ice-maker', 'Storage', '3.0 lbs bin', 3),
    ('refrigerator-001', 'door', 'Style', 'French door', 1),
    ('refrigerator-001', 'door', 'Finish', 'Fingerprint-resistant', 2),
    ('refrigerator-001', 'door', 'Hinges', 'Soft-close', 3),
    ('refrigerator-001', 'compressor', 'Type', 'Inverter compressor', 1),
    ('refrigerator-001', 'compressor', 'Efficiency', 'ENERGY STAR certified', 2),
    ('refrigerator-001', 'compressor', 'Noise', 'As low as 39 dB', 3),
    ('refrigerator-001', 'temperature-controls', 'Interface', 'Digital interior panel', 1),
    ('refrigerator-001', 'temperature-controls', 'Modes', 'Fridge, freezer, vacation', 2),
    ('refrigerator-001', 'shelves', 'Material', 'Spill-proof glass', 1),
    ('refrigerator-001', 'shelves', 'Adjustable', 'Yes', 2),
    ('refrigerator-001', 'shelves', 'Count', '4 full-width', 3),
    ('refrigerator-001', 'door-alarm', 'Trigger', 'Door open > 2 minutes', 1),
    ('refrigerator-001', 'door-alarm', 'Alert', 'Audible chime', 2),
    ('refrigerator-001', 'interior-light', 'Type', 'LED', 1),
    ('refrigerator-001', 'interior-light', 'Zones', 'Fresh food and freezer', 2);
